import type { Metadata } from "next";
import "./globals.css";
import { Box } from "@mui/material";
import DashboardSideBar from "./components/DashboardSideBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Box sx={{ display: 'flex', height: '100vh', bgcolor: '#F8F7FA' }}>
       <DashboardSideBar />
      {children}
       </Box>
      </body>
    </html>
  );
}
